apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taskboard
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Shaikh-Suja-Rahaman/devops-heros.git
    targetRevision: main
    path: session21-python/helm/taskboard
    helm:
      releaseName: taskboard
      valueFiles:
        - values-dev.yaml
        - ../../gitops/values-minikube.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: taskboard
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
