apiVersion: v1
kind: Pod

metadata:
  name: nginx-pod
  labels: #like an image tag
    app: nginx

spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80

